# ----------------------- #
#      Main Config        #
# ----------------------- #

url: http://paul.kinlan.me
title: Tales of a Developer Advocate 
subtitle: ... and other things
author: Paul Kinlan 
simple_search: http://google.com/search
description: The ramblings and musings of a Developer Advocate for Chrome at Google.

# Default date format is "ordinal" (resulting in "July 22nd 2007")
# You can customize the format as defined in
# http://www.ruby-doc.org/core-1.9.2/Time.html#method-i-strftime
# Additionally, %o will give you the ordinal representation of the day
date_format: "ordinal"

# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss: /atom.xml
subscribe_email:
# RSS feeds can list your email address if you like
email: paul.kinlan@gmail.com

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# If publishing to a subdirectory as in http://site.com/project set 'root: /project'
root: ""
permalink: /:title/
source: source/
destination: public/
plugins: source/_plugins/
category_dir: categories
markdown: kramdown
highlighter: false # default python pygments have been replaced by pygments.rb

paginate: 10          # Posts per page on the blog index
pagination_dir: blog  # Directory base for pagination URLs eg. /blog/page/2/
recent_posts: 10      # Posts in the sidebar Recent Posts section
excerpt_link: "Read on &rarr;"  # "Continue reading" link text at the bottom of excerpted articles

titlecase: true       # Converts page and post titles to titlecase

# Google Analytics
google_analytics_tracking_id: UA-114468-20


#https://github.com/mscharley/jekyll-compass
output_style: compact
sass_options:
  unix_newlines: true
gems:
- jekyll-compass


